
export const defaultAvatars: string[] = [
  'https://avatar.iran.liara.run/raster?username=Scott',
  'https://avatar.iran.liara.run/raster?username=Amy',
  'https://avatar.iran.liara.run/raster?username=James',
  'https://avatar.iran.liara.run/raster?username=Maria',
  'https://avatar.iran.liara.run/raster?username=Javier',
  'https://avatar.iran.liara.run/raster?username=Alex',
  'https://avatar.iran.liara.run/raster?username=John',
  'https://avatar.iran.liara.run/raster?username=Jane',
  'https://avatar.iran.liara.run/raster?username=Peter',
  'https://avatar.iran.liara.run/raster?username=Laura',
  'https://avatar.iran.liara.run/raster?username=Robert',
  'https://avatar.iran.liara.run/raster?username=Linda',
  'https://avatar.iran.liara.run/raster?username=Michael',
  'https://avatar.iran.liara.run/raster?username=Patricia',
  'https://avatar.iran.liara.run/raster?username=William',
  'https://avatar.iran.liara.run/raster?username=Jennifer',
  'https://avatar.iran.liara.run/raster?username=David',
  'https://avatar.iran.liara.run/raster?username=Elizabeth',
  'https://avatar.iran.liara.run/raster?username=Richard',
  'https://avatar.iran.liara.run/raster?username=Susan',
];
