
export const defaultAvatars: string[] = [
  'https://avatar.iran.liara.run/public/boy?username=Scott',
  'https://avatar.iran.liara.run/public/girl?username=Amy',
  'https://avatar.iran.liara.run/public/boy?username=James',
  'https://avatar.iran.liara.run/public/girl?username=Maria',
  'https://avatar.iran.liara.run/public/boy?username=David',
  'https://avatar.iran.liara.run/public/girl?username=Jessica',
  'https://avatar.iran.liara.run/public/boy?username=Michael',
  'https://avatar.iran.liara.run/public/girl?username=Linda',
  'https://avatar.iran.liara.run/public/boy?username=Robert',
  'https://avatar.iran.liara.run/public/girl?username=Susan',
  'https://avatar.iran.liara.run/public/boy?username=William',
  'https://avatar.iran.liara.run/public/girl?username=Karen',
  'https://avatar.iran.liara.run/public/boy?username=Richard',
  'https://avatar.iran.liara.run/public/girl?username=Patricia',
  'https://avatar.iran.liara.run/public/boy?username=Charles',
  'https://avatar.iran.liara.run/public/girl?username=Jennifer',
  'https://avatar.iran.liara.run/public/boy?username=Daniel',
  'https://avatar.iran.liara.run/public/girl?username=Elizabeth',
  'https://avatar.iran.liara.run/public/boy?username=Paul',
  'https://avatar.iran.liara.run/public/girl?username=Nancy',
];
