
export const defaultAvatars: string[] = [
  'https://api.dicebear.com/8.x/micah/svg?seed=Harley',
  'https://api.dicebear.com/8.x/micah/svg?seed=Leo',
  'https://api.dicebear.com/8.x/micah/svg?seed=Mimi',
  'https://api.dicebear.com/8.x/micah/svg?seed=Oscar',
  'https://api.dicebear.com/8.x/micah/svg?seed=Pepper',
  'https://api.dicebear.com/8.x/micah/svg?seed=Rocky',
  'https://api.dicebear.com/8.x/micah/svg?seed=Samantha',
  'https://api.dicebear.com/8.x/micah/svg?seed=Tiger',
  'https://api.dicebear.com/8.x/micah/svg?seed=Willow',
  'https://api.dicebear.com/8.x/micah/svg?seed=Zoe',
  'https://api.dicebear.com/8.x/micah/svg?seed=Max',
  'https://api.dicebear.com/8.x/micah/svg?seed=Lucy',
  'https://api.dicebear.com/8.x/micah/svg?seed=Charlie',
  'https://api.dicebear.com/8.x/micah/svg?seed=Sadie',
  'https://api.dicebear.com/8.x/micah/svg?seed=Jack',
  'https://api.dicebear.com/8.x/micah/svg?seed=Luna',
  'https://api.dicebear.com/8.x/micah/svg?seed=Toby',
  'https://api.dicebear.com/8.x/micah/svg?seed=Chloe',
  'https://api.dicebear.com/8.x/micah/svg?seed=Cody',
  'https://api.dicebear.com/8.x/micah/svg?seed=Sophie',
];
